- README.md
Removed the link and added the text ", now removed, "
> The gist mentioned in the README is no longer present / public

- spec/unit/mutant/env_spec.rb
- spec/unit/mutant/loader/eval_spec.rb
- spec/unit/mutant/parallel/worker_spec.rb
> remove duplicate definition warnings

- .travis.yml
- config/reek.yml
- config/rubocop.yml
- lib/mutant/config.rb
- lib/mutant/mutator/node/send.rb
- lib/mutant/reporter/cli/format.rb
- meta/send.rb
- mutant.gemspec
- spec/support/corpus.rb
- spec/support/rb_bug.rb
- spec/support/shared_context.rb
- spec/unit/mutant/ast_spec.rb
- spec/unit/mutant/context_spec.rb
- spec/unit/mutant/expression/method_spec.rb
- spec/unit/mutant/parallel/master_spec.rb
I want to use some 2.1 features. And no my commercial project uses < 2.1. So dropping the weight of 1.9 and 2.0 will help.
> Bump ruby requirement to 2.1

- lib/mutant.rb
- lib/mutant/expression/method.rb
- lib/mutant/expression/methods.rb
- lib/mutant/expression/namespace.rb
* Since ruby-2.1 Object.const_get does nested lookups fine
> Remove Mutant.constant_lookup

- Changelog.md
- lib/mutant/cli.rb
- spec/unit/mutant/cli_spec.rb
> Remove broken --code option

- Changelog.md
- mutant-rspec.gemspec
- spec/integration/mutant/rspec_spec.rb
- test_app/Gemfile.rspec3.3
> Support rspec 3.3

- config/flay.yml
- lib/mutant/cli.rb
- lib/mutant/matcher/compiler.rb
- lib/mutant/matcher/config.rb
- lib/mutant/reporter/cli/printer/config.rb
- spec/unit/mutant/cli_spec.rb
- spec/unit/mutant/matcher/compiler_spec.rb
- spec/unit/mutant/matcher/config_spec.rb
- spec/unit/mutant/reporter/cli/printer/config_spec.rb
- spec/unit/mutant/reporter/cli/printer/env_progress_spec.rb
- spec/unit/mutant/reporter/cli/printer/env_result_spec.rb
- spec/unit/mutant/reporter/cli/printer/status_spec.rb
- spec/unit/mutant/reporter/cli_spec.rb
> Refactor matcher config

- Changelog.md
- config/flay.yml
- lib/mutant.rb
- lib/mutant/cli.rb
- lib/mutant/matcher/compiler.rb
- lib/mutant/matcher/config.rb
- lib/mutant/repository.rb
- spec/unit/mutant/cli_spec.rb
- spec/unit/mutant/matcher/compiler_spec.rb
- spec/unit/mutant/matcher/config_spec.rb
- spec/unit/mutant/repository/diff_spec.rb
- spec/unit/mutant/repository/subject_filter_spec.rb
> Add incremental working set selection

- config/flay.yml
- lib/mutant/result.rb
- spec/unit/mutant/reporter/cli/printer/env_progress_spec.rb
- spec/unit/mutant/reporter/cli/printer/status_progressive_spec.rb
- spec/unit/mutant/reporter/cli/printer/status_spec.rb
- spec/unit/mutant/reporter/cli/printer/subject_progress_spec.rb
- spec/unit/mutant/reporter/cli_spec.rb
- spec/unit/mutant/result/env_spec.rb
> Change coverage on zero results to be 100%

- config/flay.yml
- config/reek.yml
- lib/mutant/repository.rb
- spec/unit/mutant/repository/diff_spec.rb
> Fix incremental working set on out of tree subjects

- Changelog.md
- lib/mutant/mutator/node/binary.rb
- meta/and.rb
- meta/or.rb
* Fix 287 (read the ticket if you want to complain)
> Remove invalild mutation on negating booleans

- lib/mutant/mutator/node/send.rb
- meta/send.rb
> Add mutation from to_h -> to_hash

- lib/mutant/mutator/node/defined.rb
- meta/defined.rb
> Add mutations from `defined?(foo)` to `true`, `false`

- Changelog.md
- lib/mutant/mutator/node/defined.rb
- meta/defined.rb
As a followup to #399, fixing issues I did not spotted on review.
> Cleanup defined mutations

- Changelog.md
- config/flay.yml
- lib/mutant/mutator/node/zsuper.rb
- meta/super.rb
> Add mutation `super` -> `super()`

- README.md
> Add explanation of mutation output

- Changelog.md
- config/flay.yml
- lib/mutant/reporter/cli/printer/subject_progress.rb
- spec/unit/mutant/reporter/cli/printer/status_spec.rb
- spec/unit/mutant/reporter/cli/printer/subject_progress_spec.rb
> Reduce framed progress reporter noise

- lib/mutant/mutator/node/named_value/constant_assignment.rb
- meta/casgn.rb
> Add mutation `A = true` -> `remove_const :A`

- Changelog.md
- lib/mutant/mutator/node/define.rb
- meta/def.rb
- spec/unit/mutant/subject/method/instance_spec.rb
> Add mutation `def my_method; end` -> `remove_method :my_method`

- Changelog.md
- lib/mutant/mutator/node/binary.rb
- meta/and.rb
- meta/or.rb
> Revert "Add mutations from `and`/`or` into `if`/`else`"

- lib/mutant/mutator/node/send.rb
- meta/or_asgn.rb
> Fix right hand blindspot for or-assgns

- Changelog.md
- config/flay.yml
- lib/mutant/mutator/node/block.rb
- meta/block.rb
> Add mutation `foo.baz { bar }` -> `foo.bar`

- Changelog.md
- config/flay.yml
- lib/mutant/mutator/node/named_value/access.rb
- meta/ivar.rb
- meta/op_assgn.rb
> Add mutation from `@foo` to `foo`

- README.md
In reference to https://github.com/mbj/mutant/pull/468/files#r43578087
> Add limitations section to README

- lib/mutant/cli.rb
* Introduced by new operator added since this file was touched
> Kill mutations in Mutant::CLI namespace

- spec/support/corpus.rb
> Fix API usage in corpus tests

- Changelog.md
- lib/mutant/mutator/node/send.rb
- meta/send.rb
> Add mutations from `Hash#[]` and `Hash#fetch` to `Hash#key?`

- Changelog.md
- lib/mutant/mutator/node/send.rb
- meta/send.rb
> Add mutation from `Hash#values_at` → `Hash#fetch_values`

- Changelog.md
- lib/mutant/version.rb
I also fixed some duplicated Changelog headers
> Release 0.8.9

- config/devtools.yml
- mutant.gemspec
- spec/spec_helper.rb
- spec/unit/mutant/reporter/cli/printer/mutation_result_spec.rb
* Followup with devtools 0.1.3 that fixes some behavior to be more strict
* Followup with ast-0.2.2 that changes #inspect
> Fix devtools API & external gem changes

- lib/mutant/mutator/node/send.rb
- meta/send.rb
> Add mutation from `#method` to `#public_method`

- lib/mutant/mutator/node/send.rb
- meta/send.rb
> Add mutations from #to_a => #to_set

- .rubocop.yml
- config/rubocop.yml
- lib/mutant/meta.rb
- lib/mutant/mutator/node.rb
- spec/support/corpus.rb
- spec/support/xspec.rb
- spec/unit/mutant/parallel/master_spec.rb
* Permissive semver pulled new rubocop on merge to master so fixing new
flags here explicit
> Fix rubocop complaints

- config/flay.yml
- config/rubocop.yml
- lib/mutant/color.rb
- lib/mutant/expression/namespace.rb
- lib/mutant/integration/rspec.rb
- lib/mutant/matcher/method/singleton.rb
- lib/mutant/mutator/node/named_value/access.rb
- lib/mutant/parallel/worker.rb
- lib/mutant/reporter/cli/format.rb
- lib/mutant/reporter/cli/printer.rb
- lib/mutant/reporter/cli/printer/mutation_progress_result.rb
- meta/regex.rb
- spec/support/corpus.rb
- spec/support/shared_context.rb
- spec/unit/mutant/actor/sender_spec.rb
- spec/unit/mutant/cli_spec.rb
- spec/unit/mutant/context_spec.rb
- spec/unit/mutant/env/bootstrap_spec.rb
- spec/unit/mutant/env_spec.rb
- spec/unit/mutant/integration/rspec_spec.rb
- spec/unit/mutant/isolation/fork_spec.rb
- spec/unit/mutant/matcher/methods/instance_spec.rb
- spec/unit/mutant/parallel/master_spec.rb
- spec/unit/mutant/zombifier_spec.rb
This PR contains many opinionated rubocop changes which I think represent this project's style preferences.
> Update project rubocop preferences

- config/flay.yml
- config/flog.yml
- lib/mutant/ast/meta/const.rb
- lib/mutant/ast/meta/optarg.rb
- lib/mutant/ast/meta/resbody.rb
- lib/mutant/ast/meta/restarg.rb
- lib/mutant/ast/meta/send.rb
- lib/mutant/ast/meta/symbol.rb
- lib/mutant/ast/named_children.rb
- spec/unit/mutant/ast/named_children_spec.rb
> Fix visiblity of NamedChildren methods

- README.md
Will still work with RSpec runner/config code runs
> Explain RSpec config options

- config/flay.yml
- lib/mutant.rb
- lib/mutant/cli.rb
- lib/mutant/config.rb
- spec/unit/mutant/cli_spec.rb
> Remove redundant --debug option

- lib/mutant/ast/nodes.rb
- lib/mutant/ast/types.rb
- lib/mutant/integration/rspec.rb
- lib/mutant/matcher/config.rb
- lib/mutant/mutator/node.rb
- lib/mutant/reporter/cli/printer/mutation_result.rb
- spec/support/corpus.rb
- spec/unit/mutant/context_spec.rb
- spec/unit/mutant/matcher/methods/instance_spec.rb
Introduced by new devtools release
> Fix RuboCop and Reek violations

- mutant-rspec.gemspec
- mutant.gemspec
* These files where removed from the repo since last release
> Remove TODO files from gemspecs

- Changelog.md
* Do not changelog and partially sleep
> Fix changelog date, again

- README.md
Apologies for the shitty branch name, I was lazy and used githubs web interface. Let me know if this is a problem and I'll use a better branch name.
> Add Mutant deep dive blog post to README.

- config/flay.yml
- lib/mutant/mutator/node/generic.rb
- lib/mutant/mutator/node/regexp/character_type.rb
- meta/regexp/character_types.rb
> Add \h -> \H and \H -> \h mutations

- lib/mutant/mutator/node/send.rb
- meta/send.rb
> Add `flat_map` -> `map` mutation

- lib/mutant/mutator/node/regexp/end_of_string_or_before_end_of_line_anchor.rb
Minor documentation mistake I introduced.
> Fix mistake in class annotation

- lib/mutant/mutator/node/regexp/greedy_zero_or_more.rb
- meta/regexp/regexp_greedy_zero_or_more.rb
> Add mutation for `/a*/` -> `/a/`

- .gitattributes
This is a neat trick I learned from @pocke in bbatsov/rubocop#3594. See that PR for more context
> Change merge driver for Changelog.md to union

- lib/mutant/mutator/node/define.rb
- meta/def.rb
- meta/kwarg.rb
- meta/kwoptarg.rb
- meta/rescue.rb
- meta/restarg.rb
- spec/unit/mutant/subject/method/instance_spec.rb
> Remove `remove_method` mutation

- spec/integrations.yml
As the author of the ruby spec utf-8 changes it may save you trouble if I make these PR's ?
> Update integrations.yml to reflect rubySpec update

- spec/integration/mutant/corpus_spec.rb
- spec/integrations.yml
- spec/shared/framework_integration_behavior.rb
- spec/support/corpus.rb
These are all extractions from #178
> Some maintenance

- lib/mutant/reporter/cli/printer/mutation_result.rb
- spec/unit/mutant/reporter/cli/printer/mutation_result_spec.rb
> Fix no diff hunk message to be more precise

- docs/mutant-rspec.md
Hi!
Thanks for a great gem!
Here just a small fix in docs.
> Small typo in rspec integration documentation

- lib/mutant/isolation/fork.rb
- lib/mutant/reporter/cli/printer/isolation_result.rb
- spec/unit/mutant/isolation/fork_spec.rb
> Fix waitpid calls

- lib/mutant/mutator/node/block.rb
- meta/lambda.rb
> Fix invalid block mutations on lambda

- lib/mutant/mutator/node/block.rb
- meta/block.rb
> Fix invalid block pass mutation

- lib/mutant/ast/regexp.rb
- lib/mutant/mutator/node/literal/regex.rb
- meta/regexp.rb
- spec/integrations.yml
- spec/unit/mutant/ast/regexp/parse_spec.rb
> Change to skip regexp bodies regexp_parser does not accept

- meta/file.rb
- meta/line.rb
* These where handled correctly for a while now, but we never had specs
for them.
[Fix #434]
> Add explicit support for __FILE__ and __LINE__

- README.md
> Add incremental git version requirement

- README.md
* Nobody really cares on the internals.
> Remove noise from readme

- .circleci/config.yml
* 2.6.0 on CircleCI crashes too often.
> Change back to 2.5.3 on CI

- lib/mutant.rb
- lib/mutant/isolation.rb
- lib/mutant/isolation/fork.rb
- lib/mutant/reporter/cli/printer/isolation_result.rb
- spec/integration/mutant/isolation/fork_spec.rb
- spec/support/xspec.rb
- spec/unit/mutant/isolation/fork_spec.rb
- spec/unit/mutant/isolation/result_spec.rb
- spec/unit/mutant/reporter/cli/printer/isolation_result_spec.rb
- spec/unit/mutant/reporter/cli/printer/mutation_result_spec.rb
This will help in debugging MRI crashes.
> Add killfork log capture

- lib/mutant/mutator/node/send.rb
- meta/send.rb
> Fix mutation to invalid send arguments

- docs/mutant-rspec.md
* I have no way to reach this user.
* This documented way of configuring the rspec integration is dangerous.
> Remove contribution 63a8706dcec0c933e093aec5ae35a84ca347a0b6

- docs/mutant-rspec.md
* Removes contribution tansaku@gmail.com:aeef1a0a6c671cd6b3be8f2a261bc65b34584079
* The rails docs are incomplete anyway, will be re-added in a different form
> Remove contribution aeef1a0a6c671cd6b3be8f2a261bc65b34584079

- README.md
* Removes contribution: rf@bamaru.de:8b8090b3fb71a99ae61a93ca70cc0f3edc435bd3
* Removes contribution: rf@bamaru.de:e0b388afc1a446988ece33c98305ceb8061911ca
* The inline docs are currnetly not critical, we can re-add them in a different form later
> Remove contribution

- README.md
* Removes contribution: hi@olivierlacan.com:473d63a986ccf10921ec1ceaf0913461ecb7b562
> Remove contribution 473d63a986ccf10921ec1ceaf0913461ecb7b562

- lib/mutant/mutator/node/send.rb
- meta/send.rb
* Removes contribution johncbackus@gmail.com:05b94c3264d3c0dd31d43219c345cb77e63b5780
> Remove contribution 05b94c3264d3c0dd31d43219c345cb77e63b5780

- docs/known-problems.md
* Too many contributors to remove separately.
> Remove timeout docs

- lib/mutant/mutator/node/send.rb
- meta/send.rb
* Remove contribution michael.j.herold@gmail.com:f6b9b8b095fccd248acca0b934587280d51dac28
> Remove contribution f6b9b8b095fccd248acca0b934587280d51dac28

- spec/integrations.yml
- spec/support/corpus.rb
* Removes contribution laura.paakkinen@u2i.com:3165e4f9bdf3ce091541ee5e0d66e92a8a83d06a
> Remove contribution 3165e4f9bdf3ce091541ee5e0d66e92a8a83d06a

- lib/mutant/runner.rb
- spec/unit/mutant/expression_spec.rb
* Removes contribution antondavydov.o@gmail.com:e9d5dfa9af356d20b0858bd2985b49bd113f9697
> Remove contribution e9d5dfa9af356d20b0858bd2985b49bd113f9697

- lib/mutant/mutator/node/send.rb
- meta/send.rb
* Removes contribution gperry3@asu.edu:1ad306353f0be954582d8ea6c8fbb1ad4c0c1bfb
> Remove contribution 1ad306353f0be954582d8ea6c8fbb1ad4c0c1bfb

- lib/mutant/mutator/node/class.rb
- meta/class.rb
* Removes contribution iezakrevsky@gmail.com:96fd78f302a9b6db5112cc24a4f5da33bbdcba55
> Remove contribution 96fd78f302a9b6db5112cc24a4f5da33bbdcba55

- lib/mutant/mutator/node/send.rb
- meta/send.rb
* Remove contribution 7f351fdb6a35ee6679a5bad0c8ff5eebfa3130c7:devonzuegel@gmail.com
> Remove contribution 7f351fdb6a35ee6679a5bad0c8ff5eebfa3130c7

- mutant-rspec.gemspec
- spec/integration/mutant/rspec_spec.rb
- test_app/Gemfile.rspec3.7
* Remove contribution daniel@amireh.org:ec5c8eb9b0b2c7b6832d0cd1f32cec872ccb0419
> Remove rspec 3.7 support

- docs/mutant-rspec.md
* Remove korolvs@users.noreply.github.com:f47399600523fc4a42522b54fb01b44023bd3a7a
> Remove contribution f47399600523fc4a42522b54fb01b44023bd3a7a

- bin/mutant
- lib/mutant.rb
- lib/mutant/cli.rb
- lib/mutant/config.rb
- spec/spec_helper.rb
- spec/unit/mutant/cli_spec.rb
* And kill remaining alive mutations
> Remove global usage in Mutant::CLI

- bin/mutant
- lib/mutant.rb
- lib/mutant/cli.rb
- lib/mutant/config.rb
- lib/mutant/env.rb
- lib/mutant/env/bootstrap.rb
- lib/mutant/isolation/fork.rb
- lib/mutant/matcher/method.rb
- lib/mutant/repository.rb
- lib/mutant/runner.rb
- spec/spec_helper.rb
- spec/unit/mutant/cli_spec.rb
- spec/unit/mutant/env/bootstrap_spec.rb
- spec/unit/mutant/env_spec.rb
- spec/unit/mutant/isolation/fork_spec.rb
- spec/unit/mutant/matcher/method/instance_spec.rb
- spec/unit/mutant/matcher/method/singleton_spec.rb
- spec/unit/mutant/repository/diff_spec.rb
- spec/unit/mutant/runner_spec.rb
* First step to remove all impure objects from Mutant::Config
> Add Mutant::World

- lib/mutant.rb
- lib/mutant/cli.rb
- lib/mutant/env/bootstrap.rb
- lib/mutant/integration.rb
- lib/mutant/integration/null.rb
- lib/mutant/matcher.rb
- spec/spec_helper.rb
- spec/unit/mutant/cli_spec.rb
- spec/unit/mutant/env/bootstrap_spec.rb
- spec/unit/mutant/integration_spec.rb
- spec/unit/mutant/reporter/cli/printer/config_spec.rb
- spec/unit/mutant/reporter/cli/printer/env_progress_spec.rb
- spec/unit/mutant/reporter/cli/printer/env_result_spec.rb
- spec/unit/mutant/reporter/cli/printer/status_spec.rb
- spec/unit/mutant/reporter/cli_spec.rb
* The CLIs propose is to enrich the default config with the CLI options,
not to expand the config with world state, this is the boostraps job.
> Change CLI to not do bootstrap work

- Gemfile
- Gemfile.lock
* See https://github.com/mbj/mutant/issues/957
> Change mutant license URL

- LICENSE
> Change to commercial LICENSE

- Changelog.md
- Gemfile
- Gemfile.lock
- README.md
- config/rubocop.yml
- lib/mutant/cli.rb
- lib/mutant/integration/minitest.rb
- lib/mutant/integration/rspec.rb
- lib/mutant/meta.rb
- lib/mutant/meta/example/verification.rb
- lib/mutant/mutator/node/generic.rb
- lib/mutant/mutator/node/send.rb
- lib/mutant/reporter/cli/format.rb
- lib/mutant/zombifier.rb
- mutant.gemspec
- spec/support/corpus.rb
- spec/support/ruby_vm.rb
- spec/support/shared_context.rb
- spec/support/xspec.rb
- spec/unit/mutant/repository/diff/ranges_spec.rb
> Change to allow parser 2.7 series

- .github/workflows/ci.yml
- Changelog.md
- lib/mutant/mutator/node/literal/range.rb
- meta/range.rb
> Fix endless range mutations

- Changelog.md
- Gemfile.lock
- lib/mutant/integration/minitest.rb
- lib/mutant/integration/rspec.rb
- lib/mutant/minitest/coverage.rb
- lib/mutant/selector/expression.rb
- lib/mutant/test.rb
- lib/mutant/version.rb
- spec/unit/mutant/integration/rspec_spec.rb
- spec/unit/mutant/selector/expression_spec.rb
- test_app/test/unit/test_app/literal_test.rb
This addresses #1075, but only for minitest at the moment.
Rspec integrations could also be adapted. Feel free to open an issue for this in the future.
> Add multiple cover expression support

- .rubocop.yml
* In the previous merge I accudentally merged a red PR updating rubocop.
> Fix rubocop issues

- Changelog.md
- Gemfile.lock
- lib/mutant/cli/command.rb
- lib/mutant/version.rb
- spec/unit/mutant/cli_spec.rb
> Change to display help on invalid CLI

- .github/workflows/ci.yml
- lib/mutant/config.rb
- lib/mutant/transform.rb
- spec/support/corpus.rb
- spec/unit/mutant/transform/array_spec.rb
- spec/unit/mutant/transform/bool_spec.rb
- spec/unit/mutant/transform/exception_spec.rb
- spec/unit/mutant/transform/hash_spec.rb
- spec/unit/mutant/transform/index_spec.rb
- spec/unit/mutant/transform/named_spec.rb
- spec/unit/mutant/transform/primitive_spec.rb
- spec/unit/mutant/transform/sequence_spec.rb
* This method name is more canonical for "generic do something".
> Change to Transform#call interface

- README.md
- docs/configuration.md
Adds documentation for mutant's config file format.
> Document config files

- Changelog.md
- Gemfile.lock
- lib/mutant.rb
- lib/mutant/cli/command/environment.rb
- lib/mutant/config.rb
- lib/mutant/version.rb
- spec/support/shared_context.rb
- spec/unit/mutant/cli_spec.rb
- spec/unit/mutant/config/coverage_criteria_spec.rb
- spec/unit/mutant/config_spec.rb
* I wish we had a type system and monoids.
> Fix config coverage-criteria propagation

- Changelog.md
- lib/mutant/expression/namespace.rb
- spec/unit/mutant/expression/namespace/exact_spec.rb
> Fix absent explicit fully qualified constant matching

- .rubocop.yml
- lib/mutant/reporter/cli/printer/isolation_result.rb
- spec/support/corpus.rb
- spec/unit/mutant/timer/deadline_spec.rb
- spec/unit/mutant/transform/exception_spec.rb
Simplified and adjusted some of the rubocop configuration to (imo) better fit the needs and uses of the project.
> Update rubocop config

- lib/mutant/ast/meta/send.rb
- lib/mutant/ast/types.rb
- lib/mutant/integration/minitest.rb
- lib/mutant/integration/rspec.rb
- lib/mutant/isolation/fork.rb
- lib/mutant/mutator/node/literal/symbol.rb
- lib/mutant/reporter/cli/printer/isolation_result.rb
- lib/mutant/timer.rb
- spec/support/corpus.rb
Remove various unused constants and a little bit of `private_constant` usage cleanup as well.
> Clean up constants

- lib/mutant/mutator/node/block.rb
- meta/block.rb
> Guard against mutations to loop { }

- Changelog.md
I meant to include this with #1189.
> Add missing Changelog entry

- lib/mutant/loader.rb
- lib/mutant/matcher/method/metaclass.rb
- lib/mutant/mutator/node/dynamic_literal.rb
- lib/mutant/mutator/node/sclass.rb
- lib/mutant/reporter/cli/printer/env.rb
- I found a comment or two that had drifted so I wrote a quick script to detect others and found these and resolved them.
> Fix end comments

- Changelog.md
- lib/mutant/mutator/node/literal/float.rb
- meta/float.rb
- Per https://github.com/mbj/mutant/pull/1218#issuecomment-774396841
> Remove float literal negation mutation

- Changelog.md
- Gemfile.lock
- docs/configuration.md
- lib/mutant.rb
- lib/mutant/expression/descendants.rb
- lib/mutant/matcher/descendants.rb
- lib/mutant/version.rb
- lib/mutant/world.rb
- spec/unit/mutant/expression/descendants_spec.rb
- spec/unit/mutant/matcher/descendants_spec.rb
- spec/unit/mutant/world_spec.rb
- test_app/lib/test_app.rb
> Add descendants matcher

- README.md
* All existing customers will get their previous prices. I'm
grandfathering.
> Change to new prices

- Changelog.md
- lib/mutant/cli/command/environment/run.rb
- spec/unit/mutant/cli_spec.rb
> Change to license enforcement

- Changelog.md
- lib/mutant/mutator/node/block.rb
- meta/block.rb
- Closes #1294, follow-up to #1045
> Remove mutation to `loop { nil }`

- lib/mutant/bootstrap.rb
- lib/mutant/cli/command/environment.rb
- lib/mutant/config.rb
- spec/spec_helper.rb
- spec/unit/mutant/bootstrap_spec.rb
- spec/unit/mutant/cli_spec.rb
- spec/unit/mutant/config_spec.rb
* This allows the config file loading to use the reporter.
> Change config file loading to use env

- bin/mutant
- lib/mutant.rb
- lib/mutant/cli.rb
- lib/mutant/cli/command.rb
- lib/mutant/cli/command/environment.rb
- lib/mutant/cli/command/environment/run.rb
- lib/mutant/config.rb
- spec/unit/mutant/cli_spec.rb
- spec/unit/mutant/config_spec.rb
There is lots of bitrot in this subsystem both on design and implementaiton. This improves it somewhat, not happy but its a step.
> Refactor CLI

- lib/mutant/repository/diff.rb
- spec/unit/mutant/repository/diff_spec.rb
> Add extracted Repository::Diff#touches_path

- lib/mutant/mutation/runner.rb
- lib/mutant/parallel.rb
- scripts/devloop.sh
- spec/unit/mutant/mutation/runner_spec.rb
- spec/unit/mutant/parallel_spec.rb
* This will benefit all future parallel clients, not just the mutation runner.
> Change to process warmup in parallel abstraction
