mutant.gemspec

RuboCop 0.30.1 depends on parser 2.2.2.1, which means it can’t work in a project where mutant requires parser 2.2.0.x. This allows mutant to work with parser 2.2.2.1.

Bump parser dependency to allow 2.2.2.1

---

test_app/spec/unit/test_app/literal/command_spec.rb
test_app/spec/unit/test_app/literal/string_spec.rb
test_app/spec/unit/test_app/literal_spec.rb

This code confuses me, as 99% of the time, there is a single spec per lib file.
Textmate and sublime uses this assumption to switch between tests too.
Do these really need to be separate files?
Is the problem here that the test app is too simple?

single spec for all literal tests

---

.travis.yml

* We see 50% of the builds for 2.0 failing for probably travis specific reasons.
* Other CIs / local environments are fine on 2.0

Add ruby 2.0 to allowed failures on travis

---

mutant-rspec.gemspec
mutant.gemspec

rspec integration tests are no longer in multiple files
change gemspec to reflect that fact.

Fix gemspec reference to rspec integration tests.

---

spec/unit/mutant/matcher/methods/instance_spec.rb
spec/unit/mutant/matcher/methods/singleton_spec.rb

In rspec, defining a class in a describe actually describes in the global scope (e.g. outside the describe).
So this was complaining that the class was defined multiple times. Which is true.
Just let me know where you want to move and what to call.
(probably shouldn't be defining classes in specs in general)

Move test classes (Foo, Bar) from global space to anonymous local

---

lib/mutant/reporter/cli/tput.rb
spec/unit/mutant/reporter/cli/tput_spec.rb

For some reason clr_eos on the mac responds to "cd" not "ed".
All other codes seem to respond to the cap name, but this one responds
to the tcap code
fixes #313

update tput to support terminfo on mac

---

README.md

As `mutant` is already specified as a dependency in `mutant-rspec .gemspec`, it seems unnecessary to list it in the Gemfile.

Simplify Rails setup instructions

---

config/flay.yml
lib/mutant.rb
lib/mutant/env.rb
lib/mutant/env/bootstrap.rb
lib/mutant/integration.rb
lib/mutant/integration/rspec.rb
lib/mutant/runner.rb
spec/unit/mutant/cli_spec.rb
spec/unit/mutant/env/boostrap_spec.rb
spec/unit/mutant/env_spec.rb
spec/unit/mutant/integration/rspec_spec.rb
spec/unit/mutant/integration_spec.rb
spec/unit/mutant/reporter/cli/printer/config_spec.rb
spec/unit/mutant/reporter/cli/printer/env_progress_spec.rb
spec/unit/mutant/reporter/cli/printer/env_result_spec.rb
spec/unit/mutant/reporter/cli/printer/status_spec.rb
spec/unit/mutant/reporter/cli_spec.rb
spec/unit/mutant/runner_spec.rb

* Future changes depend on this one
* Also fixes the smell of "stateless" integration objects we had in the
past

Change integrations to reference config object

---

lib/mutant/isolation.rb
spec/support/corpus.rb
spec/unit/mutant/isolation_spec.rb

This branch changes `Mutant::Isolation.call` to use block form of `IO.pipe` to ensure open file handles are closed when no longer used.

Change Mutant::Isolation.call to use block form of IO.pipe

---

config/flay.yml
config/reek.yml
lib/mutant/matcher/method.rb
lib/mutant/repository.rb
lib/mutant/subject.rb
lib/mutant/zombifier.rb
spec/shared/method_matcher_behavior.rb
spec/support/corpus.rb
spec/unit/mutant/matcher/method/instance_spec.rb
spec/unit/mutant/matcher/method/singleton_spec.rb
spec/unit/mutant/repository/diff_spec.rb

This change allows for `--since` to be used in repositories with multiple different projects and only target the code specific to a subdirectory.

Change --since to only target code under the cwd

---

config/flay.yml
lib/mutant/mutator/node/argument.rb
meta/block.rb
meta/def.rb

- Changes mutation `foo` -> `_foo` instead of `foo` -> `foo__mutant__`
- closes #292

Mutate args `foo` -> `_foo`

---

Changelog.md
config/flay.yml
lib/mutant/ast/meta.rb
lib/mutant/mutator/node/define.rb
meta/def.rb
spec/unit/mutant/ast/meta/optarg_spec.rb

WIP for #310.  I know this is ugly now. I wasn't sure though if there is a generic way that similar mutations handle this, so I figured I would ask before I invested time into a specific solution.  I'll add a few comments for things that seem strange.

Add mutation from `def foo(a = true); end` to `def foo(a = true); a = true; end`

---

Changelog.md
lib/mutant/mutator/node/send/binary.rb
meta/send.rb

Opening a WIP PR for this since I'm not sure how to go about implementing #270 at the moment.  The `mutator/node/send.rb` class seems like an inappropriate place to implement this so I wanted to get some input before I invested time on another implementation

Add a mutation from `a != b` to `!a.eql?(b)` and `!a.equal?(b)`.

---

circle.yml
config/flay.yml
lib/mutant/mutator/node/block.rb
meta/block.rb

The mutation operator from #416  was misimplemented. It lifted the inner send to have the receiver of the outer send. Not the outer send AS receiver as intended.
As a byproduct of this fix a related crash to invalid AST was fixed. The exact crash case was NOT included as a spec, because this can only happen on the unwanted mutation.

Fix mutation to invalid ast on block glueing

---

Changelog.md
lib/mutant/matcher/method.rb
lib/mutant/version.rb

* The previous regexp was ment to only match `(eval)` literally.

Correctly exclude evaled code

---

lib/mutant/mutation.rb
lib/mutant/subject/method.rb
lib/mutant/subject/method/instance.rb
lib/mutant/subject/method/singleton.rb
spec/unit/mutant/env_spec.rb
spec/unit/mutant/mutation_spec.rb
spec/unit/mutant/subject/method/instance_spec.rb
spec/unit/mutant/subject/method/singleton_spec.rb

* A relict from the days where test selection depended on this
information
* Kill mutations in Mutation#insert, also very old code.

Drop Subject#public?

---

Changelog.md
mutant-rspec.gemspec
spec/integration/mutant/rspec_spec.rb
test_app/Gemfile.rspec3.2

I do not like to carry around supports for things I do not use by myself. And enlarge CI runtime for no real gain. Updating rspec is trivial.

Drop support for rspec-3.2

---

config/flay.yml
lib/mutant/runner.rb
lib/mutant/runner/sink.rb
spec/unit/mutant/runner/sink_spec.rb
spec/unit/mutant/runner_spec.rb

* Prefer attribute reader over ivar
* Reduce intermediary unused abstract class
* Do not build a Mutant::Result::Subject in Hash default
where an empty mutation result Array is sufficient.

Kill mutations in Mutant::Runner

---

config/flay.yml
lib/mutant/mutator/node/argument.rb
lib/mutant/mutator/node/generic.rb
meta/kwarg.rb
meta/kwoptarg.rb

Adds mutations for keword arguments (closing #291):
| Source                   | Mutation                  |
| :---------------------   | :---------------------    |
| `def foo(bar:); end`     | `def foo(_bar:); end`     |
| `def foo(bar: baz); end` | `def foo(_bar: baz); end` |
| `def foo(bar: baz); end` | `def foo(bar:); end`      |

Add keword arument mutations

---

spec/integrations.yml
spec/support/corpus.rb

This change drops the concept of `excludes` from the corpus integration configuration. Instead with `permitted_errors` you specify pairs of paths and expected errors.
---
I extracted this PR from #565 which I think requires a better system for specifying what exceptions we are allowed within the corpus tests. I replaced the `exclude` configuration with `permitted_errors` because I think this is a more specific and strict guarantee for mutant's corpus tests.
---
The second commit in this PR replaces the concept of `permitted_errors` with `expected_errors`. With this change we also assert that we did not expect an error for every corpus file which did encounter an error during mutation generation.

Add "expected_errors" to corpus integrations

---

README.md

Timeout.timeout takes a timeout value in seconds, not milliseconds.

Fix timeout example parameter value

---

README.md

Commit Summary:
- Adds a link to the `slackin` invite system.
- Adds badge showing number of active users in slack.
- Adds channel listings for each `mutation-testing` channel with links.
From slack:
> @mbj: I suggest that all tools who have a channel here get PRs adding the information about the channel in the README.
I just went ahead and added *all* the channels to the README, but I don't know if that's what you wanted. Happy to update any of the wording / channel listings / etc. to your liking.
As a note, when you click on the slack badge it goes to the `mutation-testing` directly. I could, instead, make it point to the `slackin` invite server which might increase discoverability but it seemed like clicking "slack" should send you to a slack room. Let me know your preference.

Add slack invite system

---

lib/mutant/mutator/node/literal/range.rb
meta/range.rb
meta/send.rb

regarding #392 in the mutation-testing slack:
> So right now I think we should do the following:
* Remove mutations to infinite on ranges
* Lift visiblity for infinite runtime mutations in the readme
> Since I just recalled another fact: applying the N+1 mutation infinite times gives you infinite.
> @dgollahon: Feel free to submit your first PR to remove the range to infinite mutations, citing this discussion.
I don't think we discussed the `NaN` mutations, but they seemed also seemed worth removing to me while I was looking at the range mutator.
I also thought it'd be cool to get rid of emitting `nil`s in ranges, but I didn't know how to do that cleanly.
Let me know if you'd prefer the commits be squashed into one--part of why I kept them separate was because I didn't know if you'd …

Fix range mutations

---

config/flay.yml
lib/mutant.rb
lib/mutant/cli.rb
lib/mutant/config.rb
lib/mutant/reporter/cli/printer/config.rb
lib/mutant/reporter/cli/printer/env_progress.rb
lib/mutant/result.rb
spec/integrations.yml
spec/support/corpus.rb
spec/unit/mutant/cli_spec.rb
spec/unit/mutant/reporter/cli/printer/config_spec.rb
spec/unit/mutant/reporter/cli/printer/env_progress_spec.rb
spec/unit/mutant/reporter/cli/printer/env_result_spec.rb
spec/unit/mutant/reporter/cli/printer/status_progressive_spec.rb
spec/unit/mutant/reporter/cli/printer/status_spec.rb
spec/unit/mutant/reporter/cli_spec.rb
spec/unit/mutant/result/env_spec.rb

This is the most misused option I've seen so far in the wild. It does not support a good workflow. Hence killing it so users are forced to use a better strategy (exclusions) is the way to go.
I for my own projects never use this option, hence due my OSS policy it has no reason to stay.

Remove expect coverage

---

lib/mutant/mutator/node/generic.rb
lib/mutant/mutator/node/regexp.rb

Extracted from #633. For regexp mutations to be useful the node types which do not have dedicated mutators need to at least invoke the mutators for their children in order to be helpful. This change makes a separate generic mutator for regular expressions unnecessary

Remove Node::Regexp::Generic

---

lib/mutant/env/bootstrap.rb
lib/mutant/reporter/cli.rb
lib/mutant/zombifier.rb
mutant.gemspec
spec/support/warnings.yml
spec/unit/mutant/ast/regexp_spec.rb

Devtools 0.1.10 upgraded to RSpec 3.5 which broke this behavior https://github.com/mbj/mutant/blob/770f34eee55b92bf6066b13c917da50215c16dd5/spec/unit/mutant/ast/regexp_spec.rb#L73.
The second commit upgrades to the latest devtools version which upgrades reek and requires working around a few new smells. One of the smells is `InstanceVariableAssumption` which flags code that uses instance variables that were not initialized in the the `#initialize` method. I've fixed these smells by introducing private attribute readers. The other smell is a `ManualDispatch` smell which I've added a reek ignore for.
Finally, I've updated the spec warnings file to match a parser update
Extracted from #640

Upgrade to latest devtools

---

lib/mutant/mutator/node/generic.rb
lib/mutant/mutator/node/regexp/character_type.rb
meta/regexp/character_types.rb

- To reduce diff noise in following PRs and have a well-defined ordering
of nodes.

Sort regexp nodes lexicographically

---

spec/unit/mutant/reporter/cli/tput_spec.rb

Previously the spec output was spammed with
```
WARNING: `allow(...).to receive(..).ordered` is not supported and willhave no effect, use `and_return(*ordered_values)` instead.. Called from /home/dev/mutant/spec/unit/mutant/reporter/cli/tput_spec.rb:6:in `expect_command'.
```

Fix rspec warning about ordered stubs

---

lib/mutant/ast/regexp/transformer/direct.rb
lib/mutant/ast/types.rb
spec/integrations.yml
spec/unit/mutant/ast/regexp_spec.rb

This PR takes the changes in #687, fixes a bug that the upstream rubyspec changes uncovered, and adds one new exclusion to the `integrations.yml` which is visible now that utf-8 issues aren't prohibiting us from parsing the offending file

Add support for regexp_bol_escape

---

spec/integrations.yml
spec/support/corpus.rb

This PR should fix the failing build.
This file was added not long ago to the rubyspec project https://github.com/ruby/spec/blob/master/command_line/fixtures/bad_syntax.rb
In the ruby corpus specs mutant iterates on all the rubyspec files. When [`Parser::CurrentRuby.parse(path.read)`](https://github.com/mbj/mutant/blob/master/spec/support/corpus.rb#L149) hits that file a `Parser::SyntaxError` is raised.
Since the offending file was created as a fixture, mutant probably shouldn't run it? 
This PR makes the glob pattern configurable on repository level for the integrations. I'm don't know if this a direct you want to take with these specs, but I created it more to show a one way to fix this issue.

Define glob pattern for each repo

---

Gemfile.lock
circle.yml
mutant.gemspec
spec/integrations.yml
spec/support/warnings.yml

This version allows to run tests on Ruby 2.3.4.

Bump regexp_parser version to 0.4.4

---

lib/mutant/mutator/node/class.rb
meta/class.rb

Mostly for util-like classes, something lile
```ruby
class FileNameSanitizer
def self.call(file_name)
file_name.gsub(/[^0-9A-Z]/i, '_')
end
end
```
The main aim is not to change from class to module, but change way of using (initializers and so on)

Add mutation from class to module

---

spec/integrations.yml
spec/support/corpus.rb

This pull request adds exclude support to corpus and fixes the following Corpus failure:
```bash
Mutant on ruby corpus rubyspec does not fail on mutation generation
Failure/Error: node = Parser::CurrentRuby.parse(path.read)
Parser::SyntaxError:
literal contains escape sequences incompatible with UTF-8
```

Add exclude support to Corpus and fix 'literal contains escape sequences incompatible with UTF-8' Corpus failure

---

Gemfile.lock
mutant-rspec.gemspec
spec/integration/mutant/rspec_spec.rb
test_app/Gemfile.rspec3.7

This PR updates the RSpec dependency to allow RSpec`< 3.8.0`

Add support for RSpec 3.7

---

README.md

This PR changes the README document to only refer to invocations of `mutant` using `bundle exec mutant`, in order to explain what was explained well in https://github.com/mbj/mutant/issues/714#issuecomment-309754104
Hope this helps!

README: bundle exec mutant invocations only

---

config/flay.yml
lib/mutant/mutator/node/send.rb
meta/send.rb

The mutations of all calls to `#to_i` include one that mutates the call into a
call to `Integer`. This is a great mutation in all calses where there is an
explicit receiver for the `#to_i` call. However, the way that the implicit call
to `self.to_i` is parsed results in a receiver of `nil` instead of `self`.
As such, we want to limit this particular mutation to calls to `#to_i` that have
an explicit receiver. This feels like the correct behavior because the result of
the mutation would be (if it parsed): `Integer(nil)`, which doesn't retain the
intended behavior of the original source.
Another way to approach this would be to mutate the code to `Integer(self)`, but
that doesn't feel as correct to me because if you're using the implicit `self`
with a call to `#to_i`, you likely are not …

Stop mutation of `#to_i` to implicit `self`

---

lib/mutant/mutator/node/define.rb
meta/def.rb
meta/kwarg.rb
meta/kwoptarg.rb
meta/rescue.rb
meta/restarg.rb
spec/unit/mutant/subject/method/instance_spec.rb

- Mutates method bodies to `super` to catch cases where a method has
been needlessly re-implemented and the parent class provides the
equivalent behavior.
- Closes #154
- Closes #673

Add method body -> super mutation

---

Changelog.md
lib/mutant/version.rb
mutant-rspec.gemspec
spec/integrations.yml

Background:
* We hook deep into RSpec internals to get very fine grained test
selection
* These APIs are NOT public.
* Hence mutant was always very restrictive in its versioning, to not
whitelist a version where these internals are eventually changed.
* No such change happened in years.
Conclusion:
* The past approach of whitelisting rspec version after rspec version is
not the correct choice for reducing the mutant maintainership
workload.
* We'll eat the potential regression over not automatically covering new
rspec releases in the 3.x series (yeah, I know potentially last famous words).

Bump rspec dependency to cover all future 3.x releases

---

.circleci/config.yml
config/flay.yml
lib/mutant/integration/minitest.rb
lib/mutant/minitest/coverage.rb
mutant-minitest.gemspec
mutant.gemspec
spec/integration/mutant/minitest_spec.rb
spec/integrations.yml
spec/support/corpus.rb
test_app/Gemfile.minitest
test_app/test/unit/test_app/literal_test.rb

Add test minitest integration

---

lib/mutant/result.rb
lib/mutant/runner/sink.rb
spec/unit/mutant/result/env_spec.rb

* All state to compute #stop? is available on the result already, there
is no need to peek into the structure from the outside.

Change fail fast computation to reduce scope

---

lib/mutant/isolation.rb
lib/mutant/isolation/fork.rb
lib/mutant/reporter/cli/printer/isolation_result.rb
spec/unit/mutant/isolation/fork_spec.rb
spec/unit/mutant/isolation/result_spec.rb
spec/unit/mutant/reporter/cli/printer/isolation_result_spec.rb

Related to #802, first making it runtime detectable before fixing.
* It makes no sense to assume that all errors are exceptions
* This would force us to raise exceptions just to produce errors, at
control flow stages we could just return a more specialized error
instance

Improve isolation error detection

---

README.md

* Removes contribution stonecypher@gmail.com:1df1541cd6f5462b68dc83942aa8ee33c03e8052
* A reference to a removed gist is not really helpful.

Remove contribution 1df1541cd6f5462b68dc83942aa8ee33c03e8052

---

meta/def.rb

* There is no dedicated arg spec, and if we want to associate the
underscore semantics we have to mark it explicitly.

Fix def example to tag for arg mutation

---

config/rubocop.yml
meta/case.rb

* No need to globally disable it
* Be more specific

Change rubocop block length metric excludes

---

lib/mutant/transform.rb
spec/unit/mutant/transform/array_spec.rb

* Before we where only using it for checks, but never using transformed
output

Fix Mutant::Transformer::Array to actually transform

---

lib/mutant/matcher/method.rb
spec/unit/mutant/warning_filter_spec.rb

* The `kernel/` prefix was RBX specific, and we can remove it now.
* The `<intenal:prelude>` is MRI specific an we have to add it.

Fix source location blacklist to be more accurate

---

Gemfile.lock
mutant.gemspec
spec/integrations.yml

Extraction from #973
The motivation for this change is to get CI green. The details behind that are layed down in the commit message.

Change gemspec to require parser=2.6.3

---

Changelog.md
Gemfile.lock
lib/mutant/mutator/node/generic.rb
lib/mutant/registry.rb
spec/unit/mutant/registry_spec.rb

* Before this commit mutant tried to cover each node type the parser gem
may return explicitly.
* This was very useful during the pre 2.6 times when the Ruby syntax and
the parser gem had a more stable node type set to deal with.
* In recent years Ruby sadly adds lots of syntax, which means mutant
will face parser versions it was not explicitly tested with.
* This change allows mutant to co exist with any node type in the
future, while it may not do anything useful for these node types.
[Fix #1007]

Change to generic catch all node mutator

---

Changelog.md
Gemfile.lock
lib/mutant/subject/method/instance.rb
spec/unit/mutant/subject/method/instance_spec.rb

Fix memoized method subjects to preserve freezer option

---

.rubocop.yml
spec/unit/mutant/config_spec.rb
spec/unit/mutant/reporter/cli_spec.rb

- When I ran `rubocop` it spat out a large number of warnings because the configuration and inline disable comments were missing the proper namespace or did not have a namespace at all. This resolves those warnings.

Fix `rubocop` namespace warnings

---

Changelog.md
lib/mutant/mutator/node/send.rb
meta/send.rb

Mutates:
- `foo.__send__(:bar)` -> `foo.bar`
- `foo.send(:bar)` -> `foo.bar`
- `foo.public_send(:bar)` -> `foo.bar`
...and so on, including arguments.
Closes #732

Mutate dynamic send to static send

---

Changelog.md
lib/mutant/mutator/node/send.rb
meta/send.rb

- See #172. While #172 was closed outright, I think the rationale behind closing it is incorrect since the generic mutation there does not cover the proposed case. The benefit of using `[foo]` over `Array(foo)` if you have only scalar values is that you are using the simpler/narrower tool.

Mutate Array(foo) -> [foo]

---

Changelog.md
lib/mutant/mutator/node/send.rb
meta/csend.rb

- When we have an expression like `a.public_send(:b)` we convert it to the form of `a.b`. In the case of `a&.b` we had previously been emitting `a.b`, but not `a&.b`. The former is less often useful but the latter can be later promoted from `a&.b` to `a.b` if applicable since we already have a mutation to remove the conditional part of the csend.

Fix static csend mutation

---

spec/unit/mutant/bootstrap_spec.rb
spec/unit/mutant/cli_spec.rb
spec/unit/mutant/license_spec.rb
spec/unit/mutant/loader_spec.rb
spec/unit/mutant/matcher/method/instance_spec.rb
spec/unit/mutant/matcher/method/metaclass_spec.rb
spec/unit/mutant/parallel/worker_spec.rb
spec/unit/mutant/repository/diff_spec.rb
spec/unit/mutant/subject/method/instance_spec.rb
spec/unit/mutant/transform/bool_spec.rb

- Various cases of `let` statements that are never referenced, as discovered with my little [rspectre](https://github.com/dgollahon/rspectre) tool.

Remove unused `let` statements

---

Changelog.md
lib/mutant/mutator/node/block_pass.rb
meta/block_pass.rb

- Adds mutations like `map(&:to_s)` -> `map(&:to_str)`.

Add symbol-to-proc mutations

---

.github/workflows/ci.yml
Changelog.md
Gemfile.lock
docs/configuration.md
lib/mutant/config.rb
lib/mutant/result.rb
lib/mutant/version.rb
spec/support/shared_context.rb
spec/unit/mutant/result/coverage_criteria_spec.rb
spec/unit/mutant/result/mutation_spec.rb

Add abort as coverage criteria

---

Changelog.md
lib/mutant/integration/rspec.rb
mutant.yml
spec/unit/mutant/integration/rspec_spec.rb

- Allows mutant users to specify that a test covers multiple subjects using `mutant_expression`, not just one.
- Closes #1079
@mbj Is this what you had in mind in terms of implementation? I thought about concatenating the subject but then I'm not sure how you could override the default subject. I was thinking just an array of subjects would be a good starting point.
Additionally, I tried to mutate this locally but it didn't seem to pick up the subject with `--since` or a direct expression. I must be doing something wrong there--not sure if CI picked up on the changes or not.

Support multiple subject expressions [RSpec]

---

Changelog.md
Gemfile.lock
lib/mutant/mutation.rb
lib/mutant/version.rb

* It turns out that the original reason for the change to AOT
mutation details is not valid anymore after the MRI bug that causes
the VM to get stuck was reproduced outside memoizable sharing.

Change back to lazy mutation

---

Changelog.md
Gemfile.lock
lib/mutant/isolation/fork.rb
lib/mutant/version.rb
spec/unit/mutant/isolation/fork_spec.rb

This was both an MRI and a mutant problem, and its likely that the
underlying MRI problem can still manifest itself. Its now simpy just
significantly more unlikely.
A bit of context:
* Mutant is and was waiting for an FD to become readable via IO.select.
* Mutant did NOT "finish" reading the FD per IO.select return, instead
it would only read upto 4096 bytes, even if the FD could provide more
input. Mutant would loop around to call another IO.select on the FD.
* MRI does internally maintain a buffer before calling `read()` on the
underlying file descriptor. Mutant often would per IO.select only hit
that buffer, not the underlying FD.
* MRI can "forget" the Ruby side IO#read_nonblocking should not block,
so when the buffer is exhausted it may call `read()` in blocking mode.
* Mutant …

Fix stuck isolation

---

Changelog.md

- The correct destination is `.../pull/[number]`, not `.../pulls/[number]`.

Fix changelog pull request links

---

lib/mutant/mutator/node/procarg_zero.rb

- Removes an unused constant from Mutant::Mutator::Node::ProcargZero. This has not been used since #989.

Remove unused `MAP` constant

---

Changelog.md
lib/mutant/mutator/node/defined.rb
meta/defined.rb

- Mutates expressions where `defined?` is being used to check specifically for an instance variable such as `defined?(@a)` to the more narrow `instance_variable_defined?(:@a)` instead.
- Closes #1138.

Add defined? -> instance_variable_defined? mutation

---

Changelog.md
Gemfile.lock
lib/mutant/version.rb
mutant-minitest.gemspec
mutant-rspec.gemspec

* Mutant is evolving the integration interface, and will keep doing so.
* Before this change integrations would declare they can work with many
future mutant releases, but this is actually not the case.

Change to strict integration version bounds

---

lib/mutant/integration/minitest.rb
lib/mutant/integration/null.rb
lib/mutant/integration/rspec.rb
lib/mutant/result.rb
spec/support/shared_context.rb
spec/unit/mutant/integration/rspec_spec.rb
spec/unit/mutant/integration_spec.rb
spec/unit/mutant/result/test_spec.rb
test_app/Gemfile.minitest.lock
test_app/Gemfile.rspec3.8.lock

* This reduces the payload that has to be communicate from the killforks
to the main process.
* Nice increase in synthetic benchmarks.

Change to narrow test integration interface

---

Changelog.md
Gemfile.lock
lib/mutant/expression.rb
lib/mutant/expression/method.rb
lib/mutant/expression/methods.rb
lib/mutant/expression/namespace.rb
lib/mutant/result.rb
lib/mutant/test.rb
lib/mutant/version.rb
spec/unit/mutant/expression/method_spec.rb
spec/unit/mutant/expression/methods_spec.rb
spec/unit/mutant/expression/namespace/exact_spec.rb
spec/unit/mutant/expression/namespace/recursive_spec.rb
spec/unit/mutant/expression_spec.rb
test_app/Gemfile.minitest.lock
test_app/Gemfile.rspec3.8.lock

* This avoids marshalling/unmarshaling memoization caches
* The attribute is quick to precompute and not having the machinery of
memoization improves latency.

Change expression details to avoid memoization

---

spec/unit/mutant/ast/find_metaclass_containing_spec.rb

- Prior to this commit every run of `rspec spec/unit` would output the following:
> WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call. Actual error raised was #<NoMethodError: undefined method `type' for nil:NilClass>. Instead consider providing a specific error class or message. This message can be suppressed by setting: `RSpec::Expectations.configuration.on_potential_false_positives = :nothing`. Called from /Users/gollahon/oss/mutant/spec/unit/mutant/ast/find_metaclass_containing_spec.rb:16:in `block (4 levels) in <top …

Fix `rspec` error matcher warning

---

Changelog.md
lib/mutant.rb
lib/mutant/env.rb
lib/mutant/parallel.rb
lib/mutant/parallel/driver.rb
lib/mutant/parallel/worker.rb
lib/mutant/pipe.rb
lib/mutant/result.rb
lib/mutant/runner.rb
lib/mutant/runner/sink.rb
spec/support/shared_context.rb
spec/unit/mutant/env_spec.rb
spec/unit/mutant/parallel/driver_spec.rb
spec/unit/mutant/parallel/worker_spec.rb
spec/unit/mutant/parallel_spec.rb
spec/unit/mutant/pipe/connection_spec.rb
spec/unit/mutant/pipe_spec.rb
spec/unit/mutant/runner/sink_spec.rb
spec/unit/mutant/runner_spec.rb

This will include external timeouts. A work in progress.

Change process model

---

meta/regexp.rb

- These were added to account for special cases listed in the neighboring comments. Since these upstream issues have been fixed and we are pinned to a version past these, they are no longer necessary to test explicitly.

Remove outdated meta examples

---

Changelog.md
lib/mutant/mutator/node/send.rb
meta/send.rb

- Closes #689
* NOTE: I have gone with `is_a?` over `kind_of?` because [this is more commonly used](https://github.com/rubocop-hq/ruby-style-guide#is-a-vs-kind-of)

Add `a === b` -> `a.is_a?(b)` mutation

---

Changelog.md
lib/mutant/mutator/node/send.rb
meta/send.rb

- Adds mutations from predicate-like methods (methods ending in ?) to `true`/`false`
* `a.b?` -> `false`
* `a.b?` -> `true`
- Closes #263

Add predicate method mutations 

---

spec/unit/mutant/subject/method/instance_spec.rb

- This seems to be caused by stubbing `Object.const_get`. `IceNine` relies on `.const_get` to build an internal cache that it uses to perform deep freezing. This was introduced in b7c1fc788 but removing it still allows the tests to pass and gives full mutation coverage.

Fix flakey specs

---

Changelog.md
Gemfile.lock
lib/mutant/matcher/config.rb
lib/mutant/transform.rb
lib/mutant/version.rb
spec/spec_helper.rb
spec/unit/mutant/transform/block_spec.rb
test_app/Gemfile.minitest.lock
test_app/Gemfile.rspec3.8.lock

* This is a typical case where a type system would never let me go.
* And a case where mutation testing in Ruby could not even force the
`Left` here as there are no types (yet) for mutant to discover this
case.

Fix expression transform to conform to transform interface

---

meta/block.rb
meta/send.rb
spec/unit/mutant/meta/example_spec.rb

I found a couple of meta examples that were duplicated so I am removing them. I have additionally added a test to prevent this from recurring.

Remove duplicate meta examples

---

Changelog.md
lib/mutant/ast/regexp.rb
lib/mutant/mutator/node/literal/regex.rb
lib/mutant/mutator/node/send.rb
meta/send.rb
mutant.yml
spec/unit/mutant/ast/regexp/expand_regexp_ast_spec.rb

- Adds the following mutations:
* `a.match(/\Atext/)` -> `b.start_with?('text')`
* `a.match?(/\Atext/)` -> `b.start_with?('text')`
* `a =~ /\Atext/` -> `b.start_with?('text')`
- NOTE: Adds a `Mutant::AST::Regexp.expand_regexp_ast` to avoid repeating AST expansion logic in the `send` mutator. At that level, the node appears as a simple `parser` `s(:regexp ...)` node so I chose to fully parse the regexp rather than try to do a string pattern.
- Also adds following mutations:
* `a.match(/text\z/)` -> `b.end_with?('text')`
* `a.match?(/text\z/)` -> `b.end_with?('text')`
* `a =~ /text\z/` -> `b.end_with?('text')`
- Closes #169.

Add `#start_with?` and `#end_with?` mutations

---

spec/support/corpus.rb

- Mutant does not have a `Mutant::Diff` class as this was moved into `Unparser`. I have switched it to the working version and tried running with MUTANT_CORPUS_EXPENSIVE on locally.

Fix MUTANT_CORPUS_EXPENSIVE mode generation checks

---

spec/spec_helper.rb

- We are getting fairly regular CI failures where a timeout is hit but will not be hit upon rebuild. Eventually other mechanisms may be superior, but this is a helpful short-term bandaid.

Change unit spec timeout from 2s to 3s

---

Changelog.md
lib/mutant/mutator/node/send.rb

- This mutation has become very frustrating to deal with in certain situations. Notably, due to frozen string literals everywhere matching on `#equal?` one must ensure tests use unfrozen strings using `+` or other similar hacks. I also think that `#eql?` -> `#equal?` has very limited value in most situations.
- NOTE: I have left in mutations to `equal?` as long as there are alternatives to `equal?` in the possible mutations so it is not forced over `#eql?`.

Remove `#eql?` -> `#equal?` mutation

---

Changelog.md
lib/mutant/mutator/node/send.rb
meta/send.rb

Adds:
* `a.reduce(:+)`     -> `a.sum`
* `a.reduce(0, &:+)` -> `a.sum(0)`
* ...

Add `#reduce` -> `#sum` mutations

---

Changelog.md
Gemfile.lock
lib/mutant/ast/regexp/transformer.rb
lib/mutant/ast/regexp/transformer/direct.rb
lib/mutant/ast/types.rb
lib/mutant/mutator.rb
lib/mutant/registry.rb
lib/mutant/version.rb
meta/regexp/regexp_latin_property.rb
spec/unit/mutant/ast/regexp/transformer_spec.rb
spec/unit/mutant/ast/regexp_spec.rb
spec/unit/mutant/mutator_spec.rb
spec/unit/mutant/registry_spec.rb
test_app/Gemfile.minitest.lock
test_app/Gemfile.rspec3.8.lock

Fixes the `p{Latin}` regexp constructs that used to crash mutant as reported in #1231.
Also refactor the `Mutant::Registry` class to allow use case specific default behavior, making it easier to address incomplete mappings in the future.

Fix regexp mutation p{Latin}

---

Changelog.md
Gemfile.lock
lib/mutant/parallel/worker.rb
lib/mutant/pipe.rb
lib/mutant/version.rb
spec/unit/mutant/parallel/worker_spec.rb
spec/unit/mutant/pipe/connection_spec.rb
spec/unit/mutant/pipe_spec.rb
test_app/Gemfile.minitest.lock
test_app/Gemfile.rspec3.8.lock

* I got more and more reports ruby looses this flag, so taking the most
extreme action here and resetting the binmode before every IO call.

Add binmode resets before all IO calls.

---

Changelog.md
lib/mutant/mutator/node/binary.rb
meta/and.rb
meta/or.rb

[Fix #1240]
* This orthogonal is not universal, especially in assignment cases.

Remove useless binary left negation

---

.github/workflows/ci.yml
Changelog.md
README.md

* This version is EOL since EOL date: 2021-03-31

Remove support for Ruby-2.5

---

Changelog.md
lib/mutant/mutator/node/binary.rb
meta/or.rb

* Rubies syntax is not easily composable in all cases.
* Unparser should NOT make up for cases where mutant emits invalid AST
(that on the first glance should be valid, as its just promoting
expressions).

Remove invalid mutations to invalid syntax

---

Changelog.md
Gemfile.lock
lib/mutant/cli/command.rb
lib/mutant/version.rb
spec/unit/mutant/cli_spec.rb

* This reduces one cycle on customer support. Where people post an
argument error parsing issue.

Add mutant version to --help output

---

Changelog.md
lib/mutant/matcher/methods.rb
spec/unit/mutant/matcher/methods/instance_spec.rb

* At the time of Ruby 1.9 had to contnet with less coherent method
reflection. And thus was not limiting the methods per scope.
* These days the reflection interfaces are better and so not checking
the anchestors allows a small speed boost on matching.

Change to improved matching speed

---

Changelog.md
docs/commercial.md
docs/configuration.md
spec/unit/mutant/cli_spec.rb
spec/unit/mutant/config_spec.rb
spec/unit/mutant/isolation/fork_spec.rb
spec/unit/mutant/reporter/cli/printer/isolation_result_spec.rb

- A couple of these I just happened to notice while looking at the changelog
- For the remainder, I used the excellent [misspell](https://github.com/client9/misspell) tool. It might make sense to add it as a build step for mutant.

Fix various typos

---

spec/unit/mutant/bootstrap_spec.rb
spec/unit/mutant/cli_spec.rb
spec/unit/mutant/expression/descendants_spec.rb
spec/unit/mutant/meta/example_spec.rb
spec/unit/mutant/repository/diff_spec.rb
spec/unit/mutant/subject/method/instance_spec.rb
spec/unit/mutant/timer/deadline_spec.rb

- Discovered while testing a new release of [rspectre](https://github.com/dgollahon/rspectre)

Remove unused `let`s and `shared_examples`

---

.github/workflows/ci.yml
.rubocop.yml
Changelog.md
README.md
mutant-minitest.gemspec
mutant-rspec.gemspec
mutant.gemspec

* Its EOL, if you are affected support for EOL releases is not included
in commercial licenses, needs custom support agreement.

Remove ruby-2.6 support

---

lib/mutant/env.rb
lib/mutant/loader.rb
spec/unit/mutant/env_spec.rb
spec/unit/mutant/loader_spec.rb
spec/unit/mutant/mutation_spec.rb

* This makes reactions to loader results more canonical

Change to either based loader result

---

Changelog.md
lib/mutant/ast/meta/optarg.rb
lib/mutant/mutator/node/argument.rb
lib/mutant/mutator/node/arguments.rb
lib/mutant/mutator/node/procarg_zero.rb
meta/procarg_zero.rb
mutant.yml
spec/support/corpus.rb

This PR does several things, all motivated by improving procarg0 support:
- Cleans up some mutant ignores
- NOTE: Makes reliance on 2.7+ slightly tighter. Not sure if that affects any custom support cases.
- Fixes crash with certain block argument edge cases such as `foo { |(*)| }`.
- Fixes mutation from `foo { |(a, b)| }` to `foo { |(_a, b)| }` and `foo { |(a, _b)| }` instead of the less useful mutation to only `foo { |_a| }`.
- Adds a `foo { |(a, b)| }` -> `foo { |a, b| }` mutation.
- Fixes corpus tests which were previously not testing the modern `parser` AST

Improve procarg0 handling

---

Changelog.md
lib/mutant/mutator/node/regexp/named_group.rb
meta/regexp/regexp_named_group.rb

- Regular expressions such as `/(?<name>\w\d)/` would only end up mutating the part of the group (ex: `/(?<name>\W\d)/` but not `/(?<name>\w\D)/`). This change fixes that error and mutates over all children of the named capture group.

Fix named group mutations

---

Changelog.md
lib/mutant/parallel/driver.rb
lib/mutant/runner.rb
spec/support/xspec.rb
spec/unit/mutant/parallel/driver_spec.rb
spec/unit/mutant/runner_spec.rb

* Mutant will now gracefully exit on SIGINT, but still with urgency.
* All active worker threads and their child processes will get killed.
* Only currently finished mutations will be reported.
* Exit status will depend on the current results, if they are all green:
you get an exist 0, otherwise nonzero.

Add graceful exit on SIGINT

---

Changelog.md
lib/mutant/mutator/node/regexp/capture_group.rb
meta/regexp/regexp_capture_group.rb

- Fix incomplete mutations for regexp capture groups. As an example, `/(\w\d)/` now gets mutated to `/(\W\d)/` and `/(\w\D)/` instead of just the former case.
- Likewise, fix capture group -> passive group mutations which would not get properly generated in many cases. As an example, `/(\w\d)/` would get mutated to `/(?:\w)/` instead of `/(?:\w\d)/` like it will now.
- Closely related to #1328

Fix capture group mutations

---

lib/mutant/parallel/driver.rb
lib/mutant/parallel/worker.rb
spec/unit/mutant/parallel/driver_spec.rb
spec/unit/mutant/parallel/worker_spec.rb

* Before: Mutant would terminate all worker processes in sequence, while waiting for each pid to terminate separtae. This creates way more context switches than needed and resulted in a serial bottleneck.
* Now mutant signals all worker processes than collects the statuses in a secondary loop.
* Reducing this serial dependency improves mutant exit performance by several seconds on a high core cound machine, and is also measurable on more regular machines.
```
main: time bundle exec mutant run --zombie --since HEAD # 0 mutations selected.
5.69s user 4.35s system 99% cpu 10.061 total
this-branch: bundle exec mutant run --zombie --since HEAD # 0 mutations seleced.
6.23s user 50.38s system 1189% cpu 4.760 total 
```
Note for this benchmarks mutant needs to dynamically self vendor first, …

Change to more efficient worker termination

---

lib/mutant/integration/rspec.rb
spec/unit/mutant/integration/rspec_spec.rb

* Before we'd traverse the entire filtered examples explicitly removing the selection where required.
* This is inefficient especially on larger example numbers.
* The new strategy wipes all examples during setup once, and only re-enables selected examples efficiently and targeted.

Change to improved rspec example selection

---

.github/workflows/ci.yml
Changelog.md
Gemfile.lock
lib/mutant/mutator/node/if.rb
lib/mutant/version.rb
meta/if.rb
test_app/Gemfile.minitest.lock
test_app/Gemfile.rspec3.8.lock

* If its guaranteed the original code must have been a ternary, and thus will also be unparsed as a ternary: Mutant cannot delete the if or else branches.
* If its not guaranteed the original code was a ternary mutant can freely produce AST without if or else branch and unparser will know on how to generate equivalent AST.
Fixes the crashing case from: https://github.com/mbj/mutant/pull/1374 but with a smaller more localized reproduction.

Fix else/if branch deletion on ternary unparse

---

lib/mutant/bootstrap.rb
lib/mutant/env.rb
lib/mutant/hooks.rb
spec/unit/mutant/bootstrap_spec.rb
spec/unit/mutant/env_spec.rb
spec/unit/mutant/hooks_spec.rb

* Hooks where so far not yet documented so this is not a breaking change of documented public API.
* But it allows much better evolution for adding more context to the hooks in the future.

Change hooks to use kwargs

---

lib/mutant/cli/command/environment.rb
lib/mutant/config.rb
lib/mutant/matcher/config.rb
spec/unit/mutant/cli_spec.rb
spec/unit/mutant/config_spec.rb
spec/unit/mutant/matcher/config_spec.rb

* This disinfects the CLI code from dealing with config files entirely.
* Should make future extensions of config methods much easier.

Change to simplified config loading

---

Changelog.md
lib/mutant/mutation/operators.rb
meta/send.rb

Add ordering mutations

---

Changelog.md
lib/mutant/matcher/method/instance.rb

* When mutant runs zombified (for self tests) the `Zombie::Mutant` namespace tests the `Mutant` namespace.
* So when the `Zombie::Mutant` runs it has to be able to reference the "regular" `Adamantium` not the zombified when testing if a memoized method has to be unwound.

Fix zombifier on memoized methods

---

Changelog.md
Gemfile.lock
lib/mutant/cli/command/environment/test.rb
lib/mutant/cli/command/root.rb
lib/mutant/version.rb
mutant.gemspec
spec/shared/framework_integration_behavior.rb
spec/unit/mutant/cli_spec.rb
test_app/Gemfile.minitest.lock
test_app/Gemfile.rspec3.10.lock
test_app/Gemfile.rspec3.11.lock
test_app/Gemfile.rspec3.12.lock
test_app/Gemfile.rspec3.13.lock
test_app/Gemfile.rspec3.8.lock
test_app/Gemfile.rspec3.9.lock

* Mutant used to have a more "invasive" regexp-parser integration so we had to be sure there are no "new" AST nodes added between releases.
* This is gone for a longer time, so we can depend on less specific `regexp-parser` dependencies^

Upgrade regexp parser dependency
